from pathlib import Path
from PIL import Image,ImageDraw
import numpy as np,json,hashlib
R=Path('repo');P=R/'character-assets/production/20261008';P.mkdir(exist_ok=True)
n=np.array(Image.open(R/'character-assets/layers/character/base/neutral.png').convert('RGBA'));m=Image.new('L',(1448,1086));d=ImageDraw.Draw(m);d.polygon([(713,300),(875,266),(957,339),(979,432),(995,500),(985,570),(938,628),(887,655),(820,630),(744,563),(700,465),(691,365)],fill=255)
# Do not restore the old Neutral right hand/stick as an extra hand.
d.polygon([(975,412),(995,409),(1045,306),(1068,307),(1070,342),(1036,407),(1044,458),(1012,486),(998,492),(985,453),(975,435)],fill=0)
a=n.copy();mask=np.array(m)>0;mask[:350]=False;a[~mask]=0;path=R/'character-assets/layers/character/base/hair_foreground_source.png';Image.fromarray(a).save(path)
q={'status':'PIXEL_PROVENANCE_PASS_VISUAL_PENDING','copied_source':'neutral.png','pixel_mismatch':int(np.count_nonzero(np.any(a[mask]!=n[mask],axis=1))),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'policy':'Visible long hair curtain is in front of the far stick/arm where overlap occurs. Occluded stick/arm portions are deliberately invisible, not forced into front. Entirely hidden joints are excluded from visual quality judgement per user20261008. Original right-hand/stick region is excluded so no extra hand is restored. Kit original immutable.','scope':'Only source-bound updated canonical frames and Neutral; legacy unvalidated sprites are not overlaid with a differently registered hair curtain.'};(P/'qa/hair_depth_source.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
manifest=R/'character-assets/config/assets_manifest.json';j=json.loads(manifest.read_text());j['assets']=[x for x in j['assets'] if x['path']!=str(path.relative_to(R))];j['assets'].append({'path':str(path.relative_to(R)),'width':1448,'height':1086,'x':0,'y':0,'sha256':q['sha256'],'status':'IMMUTABLE_NEUTRAL_HAIR_COPY','part':'HAIR','phase':'base','hand':None,'purpose':'source-pixel curtain for physically occluded far arm/stick'});manifest.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
p=R/'site/index.html';s=p.read_text().replace('</canvas><svg id="effectLayer"','</canvas><img id="hairFrontLayer" class="character-layer hair-front-layer" alt=""><svg id="effectLayer"');p.write_text(s)
p=R/'site/styles.css';s=p.read_text();s+='\n.hair-front-layer{z-index:4;pointer-events:none}.effect-layer{z-index:5}.character-pose-label{z-index:6}\n';p.write_text(s)
p=R/'site/character-prototype.js';s=p.read_text().replace('characterFront:null,label','characterFront:null,hairFront:null,label');s=s.replace('els.drumFront.src=assetUrl', 'if(els.hairFront)els.hairFront.src=assetUrl(ASSET_ROOT+"/layers/character/base/hair_foreground_source.png");\n  els.drumFront.src=assetUrl');s=s.replace('els.characterFront=document.getElementById("characterFrontLayer");','els.characterFront=document.getElementById("characterFrontLayer");els.hairFront=document.getElementById("hairFrontLayer");');s=s.replace('els.drumFront?.addEventListener("error",fail);','els.drumFront?.addEventListener("error",fail);els.hairFront?.addEventListener("error",fail);');s=s.replace('DRUM, ASSET_ROOT+"/layers/drum/drum_foreground_occlusion.png",','DRUM, ASSET_ROOT+"/layers/drum/drum_foreground_occlusion.png", ASSET_ROOT+"/layers/character/base/hair_foreground_source.png",')
# Explicit list avoids overlaying restored original hair onto differently drawn legacy sprites.
inv=json.loads((R/'character-assets/prototypes/luna_say_maybe_16m/asset_inventory.json').read_text());keys=['SN:L','SN:R','HH:R','HH+SN:R/L','RC:R','RC+SN:R/L','RD:R','RD+SN:R/L','LT:R','LT+SN:R/L'];frames=['layers/character/base/neutral.png']
for key in keys:
 for phase in ['hit','rebound']:frames.append(inv['requiredFrames'][inv['runtimePhaseFrameMap'][key][phase]]['path'])
s=s.replace('function setFrame(path,label=', 'const sourceBoundHairFrames=new Set('+json.dumps(frames)+');\nfunction setFrame(path,label=');s=s.replace('if(!els.character)return;const src=assetUrl','if(!els.character)return;if(els.hairFront)els.hairFront.style.display=sourceBoundHairFrames.has(path)?"":"none";const src=assetUrl');p.write_text(s)
for f in ['site/index.html','site/app.js','site/character-prototype.js']:
 p=R/f;p.write_text(p.read_text().replace('20261008-lt-r5','20261008-hair-depth-r6'))
# Offline preview with new exact source curtain; source kit and character PNGs remain unchanged.
dr=Image.open(R/'character-assets/layers/drum/drum_base.png');fg=Image.open(R/'character-assets/layers/drum/drum_foreground_occlusion.png');am=Image.new('L',dr.size);ad=ImageDraw.Draw(am);ad.polygon([(420,376),(474,380),(527,454),(575,465),(615,450),(630,370),(648,317),(710,320),(716,392),(699,465),(674,513),(632,557),(602,548),(581,552),(530,551),(493,529),(480,490),(420,418)],fill=255)
for ph in ['hit','rebound']:
 c=np.array(Image.open(R/f'character-assets/layers/character/lt/{ph}_r_refresh.png'));front=c.copy();front[~(np.any(c!=n,axis=2)|(np.array(am)>0))]=0;b=Image.new('RGBA',dr.size,'white');b.alpha_composite(dr);b.alpha_composite(Image.fromarray(c));b.alpha_composite(fg);b.alpha_composite(Image.fromarray(front));b.alpha_composite(Image.fromarray(a));b.convert('RGB').save(f'work_output/previews/lt_{ph}_hair_depth.png')
print(q)
