from PIL import Image,ImageDraw
from scipy.interpolate import LinearNDInterpolator
from scipy.ndimage import map_coordinates
from pathlib import Path
import numpy as np,json,math
O=Path('work_output');(O/'variants/ht').mkdir(exist_ok=True);a=np.array(Image.open(O/'sources/neutral.png').convert('RGBA'));H,W=a.shape[:2];piv=np.array([615,510]);shift=np.array([35,17]);mask=Image.new('L',(W,H));ImageDraw.Draw(mask).polygon([(420,376),(474,380),(527,454),(576,465),(616,482),(624,535),(582,551),(540,547),(530,531),(493,529),(480,490),(420,418)],fill=255);m=np.array(mask)>0;limb=np.zeros_like(a);limb[m]=a[m];fixed=a.copy();fixed[m]=0
sy,sx=np.mgrid[340:661:5,370:721:5];points=np.column_stack([sx.ravel(),sy.ravel()]).astype(float);w=np.clip((665-points[:,0])/105,0,1);prox=points[:,0]>565;w[prox]*=np.clip((points[prox,1]-450)/40,0,1);w*=np.clip((580-points[:,1])/30,0,1);oy,ox=np.mgrid[340:661,370:721];query=np.stack([ox,oy],axis=-1)
qa={}
for phase,angle in [('hit',-20),('rebound',-40)]:
 mo=Image.fromarray(limb).rotate(angle,Image.Resampling.BICUBIC,center=tuple(piv),expand=False);tr=Image.new('RGBA',(W,H));tr.alpha_composite(mo,tuple(shift));rigid=np.array(Image.alpha_composite(Image.fromarray(fixed),tr));t=-np.deg2rad(angle)*w;rel=points-piv;dest=np.stack([np.cos(t)*rel[:,0]-np.sin(t)*rel[:,1],np.sin(t)*rel[:,0]+np.cos(t)*rel[:,1]],axis=-1)+piv+shift*w[:,None];iv=LinearNDInterpolator(dest,points)(query);bad=np.isnan(iv[:,:,0]);iv[bad]=query[bad];mesh=a.copy();mesh[340:661,370:721]=np.stack([map_coordinates(a[:,:,c].astype(float),[iv[:,:,1],iv[:,:,0]],order=1,mode='constant',cval=0) for c in range(4)],axis=-1).clip(0,255).astype('uint8');sl=Image.new('L',(W,H));ImageDraw.Draw(sl).polygon([(563,486),(606,461),(645,477),(670,513),(664,550),(639,562),(602,552),(565,545)],fill=255);mm=np.array(sl)>0;rigid[mm]=mesh[mm];im=Image.fromarray(rigid);im.save(O/f'variants/ht/{phase}_l_candidate_v1.png');dr=Image.open(O/'sources/drum_fixed.png').convert('RGBA');bg=Image.new('RGBA',(W,H),'white');bg.alpha_composite(dr);bg.alpha_composite(im);bg.convert('RGB').save(O/f'previews/ht_l_{phase}_candidate_v1.png');th=-math.radians(angle);v=np.array([444,394])-piv;tip=piv+shift+np.array([[math.cos(th),-math.sin(th)],[math.sin(th),math.cos(th)]]).dot(v);qa[phase]={'tip':tip.tolist(),'elbow':(piv+shift).tolist(),'visual_status':'PENDING'}
(O/'qa/ht_l_candidate_v1.json').write_text(json.dumps(qa,indent=2))
