from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib,shutil,re
r=next(p for p in Path(__file__).resolve().parents if (p/'character-assets').is_dir());o=r.parent/'work_output';p=r/'character-assets/production/20261008';qs=json.loads((o/'qa/remaining_11_records.json').read_text());ip=r/'character-assets/prototypes/luna_say_maybe_16m/asset_inventory.json';inv=json.loads(ip.read_text());mp=r/'character-assets/config/assets_manifest.json';m=json.loads(mp.read_text());lp=p/'ledger/motion_matrix.json';l=json.loads(lp.read_text());n=np.array(Image.open(o/'sources/neutral.png'));paths=[]
for q in qs:
 im=Image.open(o/'variants/remaining'/q['candidate']);im.load();a=np.array(im);hm=n[100:311,560:731,3]>0;assert np.array_equal(a[100:311,560:731][hm],n[100:311,560:731][hm]);assert np.array_equal(a[650:,:560],n[650:,:560]);f=inv['requiredFrames'][inv['runtimePhaseFrameMap'][q['key']][q['phase']]];dst=r/'character-assets'/f['path'];shutil.copy(o/'variants/remaining'/q['candidate'],dst);sha=hashlib.sha256(dst.read_bytes()).hexdigest();f.update(sha256=sha,state='ready',qaStatus='STATIC_VISIBLE_QA_PASS_LIVE_PENDING');paths.append(f['path'])
 for it in m['assets']:
  if it['path']==str(dst.relative_to(r)):it.update(sha256=sha,status='SOURCE_BOUND_STATIC_QA_PASS',notes=['Original head and near leg exact; local arm donor transforms only, source shoulder sleeve projection; no mirror of left/right hands; hidden hand/arm excluded from visible QA by user; kit unchanged'])
for it in l['actions']:
 if it['runtime_key'] in {q['key'] for q in qs}:it.update(status='STATIC_QA_PASSED_LIVE_PENDING',static_evidence='qa/remaining_tom_pairs_source_v1.json')
 elif it['runtime_key'].startswith('BD'):it.update(status='LIVE_QA_PASSED',runtime_evidence='qa/browser_post_promote_bd_r7.json')
q={'status':'STATIC_VISIBLE_QA_PASS_LIVE_PENDING','frames':qs,'visible_checks':['At most two hands/arms and two legs; correct source hand preserved without mirror','Source head/hair character retained, coat plaid and cuff retained','HT hit558373 left and560375 right; raised rebound','LT left hit885416, rebound856371; left hand/stick fully behind hair, no forced visibility','FT right1166555 and left1040540 on unchanged head; rebound lifts above head','Left upper sleeve source projection bends into hair; cropped-white-edge candidate rejected and source contour restored','Composite arm and foot pixel deltas disjoint; original near leg byte-exact'],'fully_hidden_anatomy':'Not assessed or reconstructed per user instruction','failed_iterations':['HT:L initial rebound rotated down; corrected direction','LT preview briefly truncated during filesystem sync; recreated and PIL fully decoded','FT:R upper-arm cut exposed a spur above hair; crop/shift hides it behind original hair'],'runtime_validation':'Pending;19 earlier pairs phase/asset verified public.'}
(p/'qa/remaining_tom_pairs_source_v1.json').write_text(json.dumps(q,ensure_ascii=False,indent=2));inv['version']+=1;inv['scope']='Luna full measures1-148;all30 source-bound static pairs60PNG;19 live pairs;11 live pairs pending';ip.write_text(json.dumps(inv,ensure_ascii=False,indent=2)+'\n');mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');lp.write_text(json.dumps(l,ensure_ascii=False,indent=2)+'\n');js=r/'site/character-prototype.js';s=js.read_text();s=re.sub(r'const sourceBoundHairFrames=new Set\((\[.*?\])\);',lambda ma:'const sourceBoundHairFrames=new Set('+json.dumps(list(dict.fromkeys(json.loads(ma[1])+paths)))+');',s);js.write_text(s)
for fn in ['site/character-prototype.js','site/app.js','site/index.html']:
 f=r/fn;f.write_text(f.read_text().replace('20261008-bd-r7','20261008-all30-r8'))
for name in ['make_ht_r_source_pair.py','make_ht_l_source_pair.py','make_ft_r_source_pair.py','make_left_toms_source_pairs.py','compose_remaining_tom_pairs.py','promote_remaining_tom_pairs.py']:shutil.copy(o/'scripts'/name,p/'scripts'/name)

res=r/'character-assets/production/WORK_RESUME_20261008.md';s=res.read_text();s='''# 作業再開入口 — 2026-10-08\n\n**現在: 全30動作のHit/Rebound60PNGを制作・静的目視QA済み。公開Webの最終全位相・再生検証は進行中。** 隠れて完全に見えない部分はユーザー指定により評価対象外。見える人体・境界・打点を確認。\n\n- 19セット38位相は公開画面で新PNG、キー、位相、前景canvas、髪レイヤー同期を検証済み。\n- 今回残り11セット22枚を反映: HT左右、LT左、FT左右、FT+SN右/左、BD+HT左右、BD+FT左右、BD+FT+SN。r8公開後に全60位相を再確認する。\n- 固定ドラム/承認NeutralのSHAは不変。各画像は元人物の局所編集、体格・頭・服・近い脚を保護。旧失敗画像は正しいdonorとして採用しない。\n- レイヤー: 固定ドラム、人物、原画由来のドラム前景、腕前景、元Neutral由来の髪前景。髪が近い箇所のスティックは髪の奥へ隠す。\n- 413過去画像の成功/失敗/保留台帳は20261008/ledger/image_audit.json。個別拡大未完了は保留のまま、成功資料にしない。\n\n## 保存場所と再開位置\n正式PNG: character-assets/layers/character/ の各楽器とcombo。\n実装: site/character-prototype.js / styles.css / index.html。\n入力仕様: 20261008/sources/WORK_MASTER_SPEC.md。指定REVISED名は素材ZIPに存在せず、同梱仕様とユーザー指示を適用。\n台帳: 20261008/ledger/motion_matrix.json。実体SHA: config/assets_manifest.json / prototypes/luna_say_maybe_16m/asset_inventory.json。\n検証: 20261008/qa/browser_post_promote_bd_r7.json / remaining_tom_pairs_source_v1.json / 各腕QA。\n局所donorと再現手順: 20261008/donors/ / scripts/。\n\n**次の作業: r8公開を確認し、全30キー60位相の正しいPNG/前景/髪同期、再生と位置移動を検証し、結果JSONと目視証跡を保存。最終検証未実施を完了扱いしない。**\n\n## 失敗と修正\nBD逆向き靴不合格→後ろから見た踵を局所donor化、ペダルへ投影。BD白い矩形継ぎ目不合格→元のふくらはぎを変形して連続接続。HT:L下向きRebound不合格→回転符号修正。FT:R髪より上の切断袖の突起不合格→隠れる位置まで局所切り出しと移動。左袖の輪郭欠損不合格→元の黒い輪郭を含む範囲へ拡大。\n\n過去の環境切断履歴: 20261008/ENVIRONMENT_STOP_CHECKPOINT.md。現環境は復旧済み。\n''';res.write_text(s);print('All30 static pairs60PNG promoted;final live QA pending')
